module:
  action: 0
  actions_permissions: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  ban: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  context: 0
  context_ui: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  help: 0
  hook_event_dispatcher: 0
  image: 0
  link: 0
  link_attributes: 0
  mailsystem: 0
  media: 0
  menu_block: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  search: 0
  sendgrid_integration: 0
  settings_tray: 0
  shortcut: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  claro: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
